version: "3.8"
services:
  service1:
    image: karljay98/transformers1
    build: ./s1
    container_name: service1
    ports:
    - published: 5000
      target: 5000
  service2:

  service3:
  service4: 