---
# tasks file for stack-deploy

- name: Deploy stack from a compose file
  docker_stack:
    state: present
    name: mystack
    compose:
      - /home/karlj/QA-practical-assessment/docker-compose.yaml